# Generated by Django 5.2.1 on 2025-05-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('percentage', models.IntegerField(help_text='Skill percentage (0-100)')),
                ('icon', models.CharField(default='fas fa-star', max_length=50)),
            ],
        ),
    ]
